/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Dominik
 */
public class Cw4 extends javax.swing.JFrame { 
    

 
 
    public boolean luhnCheck(String pesel) {
    int sum = 0, x=0;
    
    for (int i=0; i<pesel.length()-1; i++) {
        switch (x) {
            case 0: sum += Integer.parseInt(pesel.charAt(i)+"")*1;
                break;
            case 1: sum += Integer.parseInt(pesel.charAt(i)+"")*3;
                break;
            case 2: sum += Integer.parseInt(pesel.charAt(i)+"")*7;
                break;
            case 3: sum += Integer.parseInt(pesel.charAt(i)+"")*9;
                break;
            default: JOptionPane.showMessageDialog(this,"BŁĄD!");
                break;
        }
        
        x++;
        if (x==4) {
            x=0;
        }
    }
    sum += Integer.parseInt(pesel.charAt(10)+"")*1;
 
    if (sum % 10 == 0) {
    return true;
    }
    return false;
    } 
      

    public Cw4() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PESEL = new javax.swing.JFormattedTextField();
        Weryfikuj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try {
            PESEL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        PESEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESELActionPerformed(evt);
            }
        });

        Weryfikuj.setText("Weryfikuj");
        Weryfikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeryfikujActionPerformed(evt);
            }
        });

        jLabel1.setText("PESEL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PESEL, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Weryfikuj)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PESEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Weryfikuj))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PESELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PESELActionPerformed

    private void WeryfikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeryfikujActionPerformed

        if (luhnCheck(PESEL.getText())) {            
            JOptionPane.showMessageDialog(this,"Numer jest prawidłowy");
        } else {
            JOptionPane.showMessageDialog(this,"Numer jest nieprawidłowy");
        }
    }//GEN-LAST:event_WeryfikujActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cw4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cw4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cw4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cw4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new Cw4().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField PESEL;
    private javax.swing.JButton Weryfikuj;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
